"""Test script for Multi-LLM Comparison scorer."""
import asyncio
import os
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from app.services.comparison.hallucination.multi_llm_comparison import MultiLLMComparisonScorer


async def test_with_existing_responses():
    """Test multi-LLM comparison using existing responses (REAL API FLOW).
    
    This simulates the real API flow:
    1. User hits /comparison/submit with platforms: ["openai", "gemini", "groq"]
    2. API generates responses from all selected platforms
    3. When calculating scores, all_responses contains all generated responses
    4. Multi-LLM comparison uses these existing responses (NO new API calls needed)
    """
    print("\n" + "="*80)
    print("TEST 1: Real API Flow - Using Existing Responses")
    print("="*80)
    print("\n📋 Scenario: User selected [openai, gemini, groq] in /comparison/submit")
    print("   → API already generated responses from all platforms")
    print("   → all_responses contains: {openai: '...', gemini: '...', groq: '...'}")
    print("   → Multi-LLM comparison uses these existing responses (efficient!)")
    
    scorer = MultiLLMComparisonScorer()  # No ai_service needed
    
    original_prompt = "What is the capital of France and its population?"
    target_platform_id = "openai"
    
    # Simulate responses that were already generated by the API
    print("\n📝 Simulating responses already generated by API...")
    all_responses = {
        "openai": "The capital of France is Paris. The population of Paris is approximately 2.1 million people.",
        "gemini": "The capital of France is Paris. Paris has a population of around 2.1 million residents.",
        "groq": "Paris is the capital city of France. The population of Paris is about 2.1 million people."
    }
    
    print(f"\n✅ Target Platform: {target_platform_id}")
    print(f"✅ Target Response: {all_responses[target_platform_id]}")
    print(f"\n✅ Existing Responses (from API):")
    for platform, response in all_responses.items():
        if platform != target_platform_id:
            print(f"   - {platform}: {response[:80]}...")
    
    print("\n🔄 Calculating multi-LLM comparison score...")
    print("   → Using existing responses from all_responses (NO new API calls)")
    try:
        score = await scorer.calculate_score(
            target_response=all_responses[target_platform_id],
            original_prompt=original_prompt,
            target_platform_id=target_platform_id,
            judge_platform_id="openai",
            use_llm=True,
            all_responses=all_responses,  # Pass existing responses from API
        )
        
        print(f"\n✅ Score: {score}/10")
        
        # Get detailed results
        print("\n📊 Getting detailed comparison results...")
        detailed = await scorer.get_detailed_comparison(
            target_response=all_responses[target_platform_id],
            original_prompt=original_prompt,
            target_platform_id=target_platform_id,
            judge_platform_id="openai",
            use_llm=True,
            all_responses=all_responses,
        )
        
        print("\n" + "-"*80)
        print("DETAILED RESULTS:")
        print("-"*80)
        print(f"Score: {detailed['score']}/10")
        print(f"Consensus Alignment: {detailed.get('consensus_alignment', 0):.1f}%")
        print(f"Unique Claims Count: {detailed.get('unique_claims_count', 0)}")
        print(f"Contradictory Claims Count: {detailed.get('contradictory_claims_count', 0)}")
        print(f"Consensus Claims Count: {detailed.get('consensus_claims_count', 0)}")
        print(f"Reference LLMs Used: {', '.join(detailed.get('reference_llms_used', []))}")
        print(f"   → These are from existing all_responses (no new generation)")
        print(f"\nExplanation: {detailed.get('explanation', 'N/A')}")
        
        if detailed.get('unique_claims'):
            print("\n🔍 UNIQUE CLAIMS (Only in target):")
            for i, claim in enumerate(detailed['unique_claims'], 1):
                print(f"\n  {i}. Claim: {claim.get('claim', 'N/A')}")
                print(f"     Severity: {claim.get('severity', 'N/A')}")
                print(f"     Explanation: {claim.get('explanation', 'N/A')}")
        
        if detailed.get('contradictory_claims'):
            print("\n⚠️  CONTRADICTORY CLAIMS:")
            for i, claim in enumerate(detailed['contradictory_claims'], 1):
                print(f"\n  {i}. Target Claim: {claim.get('target_claim', 'N/A')}")
                print(f"     Consensus Claim: {claim.get('consensus_claim', 'N/A')}")
                print(f"     Consensus Count: {claim.get('consensus_count', 0)}")
                print(f"     Severity: {claim.get('severity', 'N/A')}")
                print(f"     Explanation: {claim.get('explanation', 'N/A')}")
        
        if detailed.get('consensus_claims'):
            print("\n✅ CONSENSUS CLAIMS (All agree):")
            for i, claim in enumerate(detailed['consensus_claims'][:5], 1):  # Show first 5
                print(f"\n  {i}. Claim: {claim.get('claim', 'N/A')}")
                print(f"     Agreement: {claim.get('agreement_count', 0)}/{claim.get('total_responses', 0)}")
        
        print("\n✅ SUCCESS: Used existing responses from all_responses (efficient!)")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()


async def test_with_contradictory_response():
    """Test with a response that has contradictions."""
    print("\n" + "="*80)
    print("TEST 2: Testing with Contradictory Response")
    print("="*80)
    
    scorer = MultiLLMComparisonScorer()
    
    original_prompt = "What is the population of Tokyo, Japan?"
    target_platform_id = "openai"
    
    # Simulate responses where target has different/contradictory information
    all_responses = {
        "openai": "Tokyo, Japan has a population of 15 million people. It is the largest city in Japan.",
        "gemini": "Tokyo, the capital of Japan, has a population of approximately 14 million residents.",
        "groq": "The population of Tokyo, Japan is around 14 million people."
    }
    
    print(f"Target Platform: {target_platform_id}")
    print(f"Target Response: {all_responses[target_platform_id]}")
    print(f"\nReference Responses:")
    for platform, response in all_responses.items():
        if platform != target_platform_id:
            print(f"  - {platform}: {response}")
    
    print("\n🔄 Calculating multi-LLM comparison score...")
    try:
        detailed = await scorer.get_detailed_comparison(
            target_response=all_responses[target_platform_id],
            original_prompt=original_prompt,
            target_platform_id=target_platform_id,
            judge_platform_id="openai",
            use_llm=True,
            all_responses=all_responses,
        )
        
        print("\n" + "-"*80)
        print("DETAILED RESULTS:")
        print("-"*80)
        print(f"Score: {detailed['score']}/10")
        print(f"Consensus Alignment: {detailed.get('consensus_alignment', 0):.1f}%")
        print(f"Unique Claims Count: {detailed.get('unique_claims_count', 0)}")
        print(f"Contradictory Claims Count: {detailed.get('contradictory_claims_count', 0)}")
        
        if detailed.get('contradictory_claims'):
            print("\n⚠️  CONTRADICTORY CLAIMS DETECTED:")
            for i, claim in enumerate(detailed['contradictory_claims'], 1):
                print(f"\n  {i}. Target: {claim.get('target_claim', 'N/A')}")
                print(f"     Consensus: {claim.get('consensus_claim', 'N/A')}")
                print(f"     Severity: {claim.get('severity', 'N/A')}")
                print(f"     Explanation: {claim.get('explanation', 'N/A')}")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()


async def test_generating_new_responses():
    """Test generating new responses when user only selected 1 platform (FALLBACK CASE).
    
    NOTE: This is a FALLBACK scenario. In normal API flow:
    - User selects multiple platforms → responses already generated → use those
    - This test only runs if user selected only 1 platform (rare case)
    """
    print("\n" + "="*80)
    print("TEST 3: Fallback - Generating New Responses (User Selected Only 1 Platform)")
    print("="*80)
    print("\n⚠️  NOTE: This is a FALLBACK case. In normal flow, user selects multiple platforms.")
    print("   → If user selects only 1 platform, we generate from remaining LLMs")
    print("   → This requires API keys and makes additional API calls")
    print("   → In production, users typically select 2-3 platforms")
    
    scorer = MultiLLMComparisonScorer()
    
    original_prompt = "Explain quantum computing in simple terms."
    target_platform_id = "openai"
    
    # Simulate only target response available (user selected only 1 platform)
    all_responses = {
        "openai": "Quantum computing uses quantum mechanical phenomena like superposition and entanglement to perform computations. Unlike classical computers that use bits (0 or 1), quantum computers use qubits that can exist in multiple states simultaneously."
    }
    
    print(f"\n📋 Scenario: User selected only [{target_platform_id}]")
    print(f"   → Only 1 response available in all_responses")
    print(f"   → Will generate from remaining LLMs (gemini, groq)")
    
    print(f"\nTarget Platform: {target_platform_id}")
    print(f"Target Response: {all_responses[target_platform_id][:100]}...")
    
    # Check for API keys
    has_openai = bool(os.getenv("OPENAI_API_KEY"))
    has_gemini = bool(os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY"))
    has_groq = bool(os.getenv("GROQ_API_KEY"))
    
    print(f"\n🔑 API Keys Available:")
    print(f"   - OpenAI: {'✅' if has_openai else '❌'}")
    print(f"   - Gemini: {'✅' if has_gemini else '❌'}")
    print(f"   - Groq: {'✅' if has_groq else '❌'}")
    
    if not (has_gemini or has_groq):
        print("\n⚠️  WARNING: No API keys for gemini/groq. This test will fail.")
        print("   Set GEMINI_API_KEY or GROQ_API_KEY to test fallback generation.")
        return
    
    print("\n🔄 Calculating multi-LLM comparison score (will generate new responses)...")
    try:
        detailed = await scorer.get_detailed_comparison(
            target_response=all_responses[target_platform_id],
            original_prompt=original_prompt,
            target_platform_id=target_platform_id,
            judge_platform_id="openai",
            use_llm=True,
            all_responses=all_responses,  # Only has target response
        )
        
        print("\n" + "-"*80)
        print("DETAILED RESULTS:")
        print("-"*80)
        print(f"Score: {detailed['score']}/10")
        print(f"Consensus Alignment: {detailed.get('consensus_alignment', 0):.1f}%")
        print(f"Reference LLMs Used: {', '.join(detailed.get('reference_llms_used', []))}")
        print(f"\nExplanation: {detailed.get('explanation', 'N/A')[:200]}...")
        
        if detailed.get('reference_llms_used'):
            print(f"\n✅ Successfully generated responses from: {', '.join(detailed['reference_llms_used'])}")
        else:
            print(f"\n⚠️  No reference responses generated (check API keys and rate limits)")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        print("\n💡 Tip: In production, users select multiple platforms, so this fallback is rarely needed.")
        import traceback
        traceback.print_exc()


async def test_with_unique_claims():
    """Test with response containing unique claims not in other responses."""
    print("\n" + "="*80)
    print("TEST 4: Testing with Unique Claims (Potential Hallucinations)")
    print("="*80)
    
    scorer = MultiLLMComparisonScorer()
    
    original_prompt = "Tell me about the history of the Eiffel Tower."
    target_platform_id = "openai"
    
    # Target has unique claim that others don't have (potential hallucination)
    all_responses = {
        "openai": "The Eiffel Tower was built in 1889 for the World's Fair. It was designed by Gustave Eiffel. The tower was originally painted red and was the tallest structure in the world at the time.",
        "gemini": "The Eiffel Tower was constructed in 1889 for the Exposition Universelle. It was designed by engineer Gustave Eiffel.",
        "groq": "Built in 1889, the Eiffel Tower was created for the World's Fair. Gustave Eiffel was the engineer behind its design."
    }
    
    print(f"Target Platform: {target_platform_id}")
    print(f"Target Response: {all_responses[target_platform_id]}")
    print(f"\nNote: Target mentions 'originally painted red' which other responses don't mention")
    
    print("\n🔄 Calculating multi-LLM comparison score...")
    try:
        detailed = await scorer.get_detailed_comparison(
            target_response=all_responses[target_platform_id],
            original_prompt=original_prompt,
            target_platform_id=target_platform_id,
            judge_platform_id="openai",
            use_llm=True,
            all_responses=all_responses,
        )
        
        print("\n" + "-"*80)
        print("DETAILED RESULTS:")
        print("-"*80)
        print(f"Score: {detailed['score']}/10")
        print(f"Unique Claims Count: {detailed.get('unique_claims_count', 0)}")
        
        if detailed.get('unique_claims'):
            print("\n🔍 UNIQUE CLAIMS DETECTED (Potential Hallucinations):")
            for i, claim in enumerate(detailed['unique_claims'], 1):
                print(f"\n  {i}. Claim: {claim.get('claim', 'N/A')}")
                print(f"     Severity: {claim.get('severity', 'N/A')}")
                print(f"     Explanation: {claim.get('explanation', 'N/A')}")
        
    except Exception as e:
        print(f"\n❌ Error: {str(e)}")
        import traceback
        traceback.print_exc()


async def test_edge_cases():
    """Test edge cases."""
    print("\n" + "="*80)
    print("TEST 5: Edge Cases")
    print("="*80)
    
    scorer = MultiLLMComparisonScorer()
    
    # Test with no reference responses available
    print("\n📝 Test 5a: No reference responses available")
    try:
        detailed = await scorer.get_detailed_comparison(
            target_response="Test response",
            original_prompt="Test prompt",
            target_platform_id="openai",
            judge_platform_id="openai",
            use_llm=True,
            all_responses={"openai": "Test response"},  # Only target, no references
        )
        print(f"✅ Handled gracefully - Score: {detailed['score']}/10")
        print(f"   Explanation: {detailed.get('explanation', 'N/A')[:100]}...")
    except Exception as e:
        print(f"❌ Error: {str(e)}")
    
    # Test with use_llm=False (should raise error)
    print("\n📝 Test 5b: use_llm=False (should raise ValueError)")
    try:
        await scorer.calculate_score(
            target_response="Test",
            original_prompt="Test",
            target_platform_id="openai",
            use_llm=False,
        )
        print("❌ Should have raised ValueError")
    except ValueError as e:
        print(f"✅ Correctly raised ValueError: {str(e)}")
    except Exception as e:
        print(f"❌ Unexpected error: {str(e)}")


async def main():
    """Run all tests."""
    print("\n" + "="*80)
    print("MULTI-LLM COMPARISON SCORER TEST SUITE")
    print("="*80)
    print("\n📋 HOW IT WORKS IN REAL API FLOW:")
    print("  1. User hits /comparison/submit with platforms: [openai, gemini, groq]")
    print("  2. API generates responses from all selected platforms")
    print("  3. all_responses = {openai: '...', gemini: '...', groq: '...'}")
    print("  4. Multi-LLM comparison uses existing responses (NO new API calls)")
    print("  5. Only generates new responses if user selected < 2 platforms (fallback)")
    
    # Check for OpenAI API key (needed for judge)
    if not os.getenv("OPENAI_API_KEY"):
        print("\n⚠️  WARNING: OPENAI_API_KEY not set. Judge comparison will fail.")
        print("   Set it in your environment or .env file")
    
    # Run main test (real API flow)
    print("\n" + "="*80)
    print("RUNNING MAIN TEST (Real API Flow)")
    print("="*80)
    await test_with_existing_responses()
    
    # Run additional scenario tests
    print("\n" + "="*80)
    print("RUNNING SCENARIO TESTS")
    print("="*80)
    await test_with_contradictory_response()
    await test_with_unique_claims()
    
    # Optional: Test fallback generation (only if user wants)
    print("\n" + "="*80)
    print("OPTIONAL: FALLBACK TEST (User Selected Only 1 Platform)")
    print("="*80)
    print("⚠️  This test generates new responses (requires API keys)")
    print("   In production, users typically select 2-3 platforms, so this is rare.")
    response = input("\nRun fallback generation test? (y/n): ").strip().lower()
    if response == 'y':
        await test_generating_new_responses()
    else:
        print("Skipping fallback generation test.")
    
    # Run edge case tests
    print("\n" + "="*80)
    print("RUNNING EDGE CASE TESTS")
    print("="*80)
    await test_edge_cases()
    
    print("\n" + "="*80)
    print("TEST SUITE COMPLETE")
    print("="*80)
    print("\n💡 KEY TAKEAWAY:")
    print("   In production API flow, multi-LLM comparison uses existing responses")
    print("   from all_responses (efficient, no extra API calls).")
    print("   Fallback generation only happens if user selected < 2 platforms.")


if __name__ == "__main__":
    asyncio.run(main())
